#! /bin/sh
#
# Copyright 2014 Oly Project
#
# See LICENSE for licensing terms.

# Load the test library.
. "$SOURCE/tap/libtap.sh"

# Plan test.
plan 2
ok_program 'With real env.' 0 '' "$BUILD/oly/core/c-oget_home"
HOMEHOLD=$HOME
export HOME=/fakehome
ok_program 'With fake env.' 1 '' "$BUILD/oly/core/c-oget_home"
export HOME=$HOMEHOLD
unset HOMEHOLD
