## i18n, both for tests and the main library.

## can also be a dll, static or files 
I18N_MODE								= common

MAIN_I18N_OUTPUT				= i18n/$(OLY_I18N_NAME).dat
TEST_I18N_OUTPUT				= tests/data/i18n/$(OLY_I18N_NAME).dat
I18N_DEPSDIR						= .i18ndeps
TEST_I18N_DEPSDIR				= .testi18ndeps
INDEX_NAME							=	res_index
I18N_INDEX							= i18n/$(INDEX_NAME)

MAIN_OUTDIR							= $(abs_top_builddir)/i18n/
TEST_OUTDIR							= $(abs_top_builddir)/tests/data/i18n/

MAIN_I18N_INDEX_TXT			= $(addsuffix .txt,$(I18N_INDEX))
TEST_I18N_INDEX_TXT			= $(addprefix tests/data/,$(MAIN_I18N_INDEX_TXT))
MAIN_I18N_INDEX					= $(addsuffix .res,$(I18N_INDEX))
TEST_I18N_INDEX					= $(addprefix tests/data/,$(MAIN_I18N_INDEX))
MAIN_I18N_TXT 					= $(addsuffix .txt,$(MAIN_I18N))
TEST_I18N_TXT 					= $(addsuffix .txt,$(TEST_I18N))
MAIN_I18N_RES 					= $(addsuffix .res,$(MAIN_I18N)) $(MAIN_I18N_INDEX)
TEST_I18N_RES 					= $(addsuffix .res,$(TEST_I18N)) $(TEST_I18N_INDEX)

MAIN_I18N_BUILT					= $(MAIN_I18N_INDEX_TXT) $(MAIN_I18N_INDEX) i18n/res_list.txt 
TEST_I18N_BUILT					= $(addprefix tests/data/,$(MAIN_I18N_BUILT))
MAIN_I18N_CLEAN					= $(MAIN_I18N_RES) $(MAIN_I18N_BUILT) $(I18N_DEPSDIR)
TEST_I18N_CLEAN					= $(TEST_I18N_RES) $(TEST_I18N_BUILT) $(TEST_I18N_DEPSDIR)

# pkgdata version.
PKGDATAOPTS							=	-s $(abs_top_builddir) --name $(OLY_I18N_NAME) \
													--mode $(I18N_MODE) -e $(OLY_I18N_NAME) -v

MAIN_PKGDATAOPTS				= $(PKGDATAOPTS) -d $(MAIN_OUTDIR) --tempdir $(I18N_DEPSDIR)
TEST_PKGDATAOPTS				= $(PKGDATAOPTS) -d $(TEST_OUTDIR) --tempdir $(TEST_I18N_DEPSDIR)

GENRBOPT								= -s $(abs_top_srcdir) --bundle-name $(OLY_I18N_NAME)

MAIN_GENRBOPT						= $(GENRBOPT) -d $(MAIN_OUTDIR)
TEST_GENRBOPT						= $(GENRBOPT) -d $(TEST_OUTDIR)

i18n-main-built-clean:
	$(RMV) -rf $(MAIN_I18N_BUILT) $(I18N_DEPSDIR)
	$(MKDIR_P) $(I18N_DEPSDIR)

i18n-test-built-clean:
	$(RMV) -rf $(TEST_I18N_BUILT) $(TEST_I18N_DEPSDIR) 
	$(MKDIR_P) $(TEST_I18N_DEPSDIR)

## if the build_index breaks again this is useful for looking at the vars.

$(MAIN_I18N_INDEX_TXT): i18n-main-built-clean
	@echo "generating $@ (list of installed language name locales)"; \
	echo "// Warning this file is automatically generated" > $@; \
	echo "$(INDEX_NAME):table(nofallback) {" >> $@; \
	echo "    InstalledLocales {" >> $@; \
	for file in $(notdir $(MAIN_I18N)) ; do \
		echo "        $$file {\"\"}" >> $@; \
	done; \
	echo "    }" >> $@; \
	echo "}" >> $@;

$(TEST_I18N_INDEX_TXT): i18n-test-built-clean
	@echo "generating $@ (list of installed language name locales)"; \
	echo "// Warning this file is automatically generated" > $@; \
	echo "$(INDEX_NAME):table(nofallback) {" >> $@; \
	echo "    InstalledLocales {" >> $@; \
	for file in $(notdir $(TEST_I18N)) ; do \
		echo "        $$file {\"\"}" >> $@; \
	done; \
	echo "    }" >> $@; \
	echo "}" >> $@;

## this worked before. Shrug.
$(MAIN_I18N_INDEX): $(MAIN_I18N_INDEX_TXT)
	@echo "generating $@"
		$(GENRB) $(MAIN_GENRBOPT) $(MAIN_I18N_TXT) $(MAIN_I18N_INDEX_TXT)

$(TEST_I18N_INDEX): $(TEST_I18N_INDEX_TXT)
	@echo "generating $@"
		$(GENRB) $(TEST_GENRBOPT) $(TEST_I18N_TXT) $(TEST_RES_INDEX)

i18n/res_list.txt: $(MAIN_I18N_INDEX) 
	ls $(MAIN_I18N_RES) > $@

tests/data/i18n/res_list.txt: $(TEST_I18N_INDEX)
	ls $(TEST_I18N_RES) > $@

$(MAIN_I18N_OUTPUT): i18n/res_list.txt
	$(PKGDATA) $(MAIN_PKGDATAOPTS) i18n/res_list.txt  

$(TEST_I18N_OUTPUT): tests/data/i18n/res_list.txt
	$(PKGDATA) $(TEST_PKGDATAOPTS) tests/data/i18n/res_list.txt

# end of i18n.
