#! /bin/sh
#
# Copyright 2014 Oly Project
#
# See LICENSE for licensing terms.

# Load the test library.
. "$SOURCE/tap/libtap.sh"

# Plan test.
plan 3
ok_program 'Zero args.' 0 '' "$BUILD/oly/io/c-oly_getOCharArgs"
ok_program 'One arg.' 0 '' "$BUILD/oly/io/c-oly_getOCharArgs Argo"
ok_program 'Many args.' 0 '' "$BUILD/oly/io/c-oly_getOCharArgs Argo Nautica -h -i -v vee beee"

