Oly
===
:description: Oly data mover goals and timeline
:keywords:    Oly, CSV parser, goals, import, text
:title:       Oly (main page)
:icons:
ifdef::is_standalone[]
:iconsdir:  icons
:imagesdir: images
:icons:
:toc2:
endif::is_standalone[]
ifdef::is_fossil[]
:iconsdir:  /docs/tip/docs/icons
:imagesdir: /docs/tip/docs/images
:icons:
endif::is_fossil[]

Current Features
----------------
* Internal node queue and string buffer
* Node hierarchy preserved and sent through
* Data source interface for external sources
* Boundary buffers to transfer external encodings/character sets to internal (ICU) encoding and back again.
* Storage for several different types of data in each node.
* SHA3 hash function built in and ready for use.
* Polyglot (that is, translatable) error handling

Goals
-----
. Finish Oly 1.0

Projects 
--------
. Commit to core API design and code it.
. Clean up existing work 
. Write tests for all facets of core API.
. Establish what "finish" means.

Tasks
-----
. Commit to and code core API
  .. Top level configuration file loading and storage (due Friday, 4-18-14)
  .. OlyString.  Will be a dictionary.  Where will it be used and how?  Tags, Anchors, Aliases, etc.
  .. Table data source input objects.  Columns, rows, tables, etc.
  .. Flesh out data source dequeue and extract functions.
. Clean up existing work
  .. Better buffering on external interfaces (SQLite is very slow with no buffer).
  .. Remove unneeded data source and node functions.  Define clearer boundaries between these objects.
  .. Bring doc and lib Makefile.am into main directory.
  .. String buffer has some problems.  Runs too many times.  Could use debugging.
  .. Remove unused errors.
  .. Clean up core library.  All tests link to core, core is huge.  Lighten it.
  .. error handling for library interfaces.  Should use translatable strings stored in the i18n folder.
  .. Organize functions in files better.
  .. Verify destructor functions free all memory, and that they are called when they should be.
. Establish what "finish" means
  .. Set release date.
  .. Commit to features for release date.

// vim: set syntax=asciidoc:
